all: randomtestcard1 randomtestcard2 randomtestadventurer 

randomtestcard1:
	g++ -o randomtest1 -g randomtestcard1.c dominion.c dominion.h -Wall -fpic -coverage -lm

randomtestcard2:
	g++ -o randomtest2 -g randomtestcard2.c dominion.c dominion.h -Wall -fpic -coverage -lm

randomtestadventurer:
	g++ -o randomadventurer -g randomtestadventurer.c dominion.h -Wall -fpic -coverage -lm

