CFLAGS= -Wall -fpic -coverage -lm -std=c99

unittestresults: maintest.c unittest1.c unittest2.c unittest3.c unittest4.c
	gcc -o unittestresults maintest.c unittest1.c unittest2.c unittest3.c unittest4.c -I.

